SistemaRestaurante/Source/Presentation Layer/SistemaRestaurante.WebSite/Controllers/LocalController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SistemaRestaurante.Utils;

namespace SistemaRestaurante.WebSite.Controllers
{
    using SistemaRestaurante.BusinessLogic;
    using SistemaRestaurante.BusinessEntity;

      [Authorize]
    public class LocalController : Controller
    {
        //
        // GET: /Local/

        public ActionResult Index()
        {
           
            return View("ListadoJqgrid");
        }

       [HttpPost]
        public JsonResult Listar(string sidx, string sord, int page, int rows, bool _search, string searchField, string searchOper, string searchString)
        {
            var jqgrid = new JQgrid();
            IList<Local> lista = new List<Local>();
            var where = string.Empty;

            try
            {
                if (_search)
                {
                    where = where + GetWhere(searchField, searchOper, searchString);
                }

                var totalPages = 0;
                var count = LocalBL.Instancia.Count(where);

                if (count > 0 && rows > 0)
                {
                    totalPages = count / rows;
                    totalPages = totalPages == 0 ? 1 : totalPages;
                }

                page = page > totalPages ? totalPages : page;

                var start = rows * page - rows;
                if (start < 0) start = 0;

                jqgrid.total = totalPages;
                jqgrid.page = page;
                jqgrid.records = count;
                jqgrid.start = start;

                lista = LocalBL.Instancia.Listar(sidx, sord, rows, start, count, where);

                var filas = new List<JRow>();

                foreach (var local in lista)
                {
                    filas.Add(new JRow
                                  {
                                      id = local.IdLocal,
                                      cell = new string[]
                                                 {
                                                     local.IdLocal.ToString(),
                                                     local.Nombre,
                                                     local.Direccion,
                                                     local.Distrito,
                                                     local.Telefono,
                                                 }
                                  });
                }

                jqgrid.rows = filas.ToArray();
                return Json(jqgrid);
            }
            catch (Exception ex)
            {
                throw new Exception(ex.Message);
            }
        }


          public ActionResult Create()
        {
            var local = new Local();

            var provincias = new List<SelectListItem>();
            provincias.Add(new SelectListItem{ Text = "Lima", Value = "Lima"});
            provincias.Add(new SelectListItem { Text = "Trujillo", Value = "Trujillo" });
            provincias.Add(new SelectListItem { Text = "Canta", Value = "Canta" });
            provincias.Add(new SelectListItem { Text = "Huaral", Value = "Huaral" });
            ViewBag.Provincias = new SelectList(provincias, "Value", "Text");
            return View("Create", local);
        }

        public JsonResult Distritos(string id)
        {
            var distritos = new List<SelectListItem>();
            if(id == "Lima")
            {
                distritos.Add(new SelectListItem{ Text = "Jesus Maria", Value = "Jesus Maria"});
                distritos.Add(new SelectListItem { Text = "San Isidro", Value = "San Isidro" });

            }
            else
            {
                if(id=="Trujillo")
                {
                    distritos.Add(new SelectListItem { Text = "Salaverry", Value = "Salaverry" });
                    distritos.Add(new SelectListItem { Text = "Florencia", Value = "Florencia" });

                }
            }
            return Json(new SelectList(distritos, "Value", "Text"), JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult Create(Local local)
        {
            LocalBL.Instancia.Agregar(local);

            var lista = LocalBL.Instancia.Listar();
            return View("Listado", lista);
        }

        public ActionResult Edit(int idLocal)
        {
            var local = LocalBL.Instancia.Obtener(idLocal);

            return View("Edit", local);

        }

        [HttpPost]
        public ActionResult Edit(Local local)
        {
            LocalBL.Instancia.Modificar(local);

            var lista= LocalBL.Instancia.Listar();
            return View("Listado", lista);
        }

        public ActionResult Delete(int idLocal)
        {
            var local = LocalBL.Instancia.Obtener(idLocal);

            return View("Delete", local);
        }

        [HttpPost]
        public ActionResult Delete(Local local)
        {
            LocalBL.Instancia.Eliminar(local.IdLocal);

            var lista= LocalBL.Instancia.Listar();
            return View("Listado", lista);
        }

        public ActionResult Details(int idLocal)
        {
            var local = LocalBL.Instancia.Obtener(idLocal);

            return View("Details", local);
        }


        protected String GetWhere(string columna, string operacion, string valor)
        {
            var opciones = new Dictionary<string, string>
                               {
                                   {"eq", "="},
                                   {"ne", "<>"},
                                   {"lt", "<"},
                                   {"le", "<="},
                                   {"gt", ">"},
                                   {"ge", ">="},
                                   {"bw", "LIKE"},
                                   {"bn", "NOT LIKE"},
                                   {"in", "LIKE"},
                                   {"ni", "NOT LIKE"},
                                   {"ew", "LIKE"},
                                   {"en", "NOT LIKE"},
                                   {"cn", "LIKE"},
                                   {"nc", "NOT LIKE"}
                               };

            if (operacion.Equals("bw") || operacion.Equals("bn"))
            {
                valor = valor + "%";
            }
            if (operacion.Equals("ew") || operacion.Equals("en"))
            {
                valor = "%" + valor;
            }
            if (operacion.Equals("cn") || operacion.Equals("nc") || operacion.Equals("in") || operacion.Equals("ni"))
            {
                valor = "%" + valor + "%";
            }
            if (opciones.Take(6).ToDictionary(p => p.Key, p => p.Value).ContainsKey(operacion))
            {
                return string.IsNullOrWhiteSpace(valor)
                           ? string.Empty
                           : columna + " " + opciones[operacion] + " " + valor;
            }
            return columna + " " + opciones[operacion] + " '" + valor + "'";
        }

          [HttpPost]
          public JsonResult CreateJqGrid(Local local)
          {
              var jsonResponse = new JsonResponse();
              try
              {
                  LocalBL.Instancia.Agregar(local);
                  jsonResponse.Success = true;
                  jsonResponse.Message = "Se registro satisfactoriamente";

              }
              catch (Exception ex)
              {
                  jsonResponse.Success = false;
                  jsonResponse.Message = "No se pudo agregar el registro." + ex.Message;
              }
              return Json(jsonResponse, JsonRequestBehavior.AllowGet);
          }

          [HttpPost]
          public JsonResult EditJqGrid(Local local)
          {
              var jsonResponse = new JsonResponse();
              try
              {
                  LocalBL.Instancia.Modificar(local);
                  jsonResponse.Success = true;
                  jsonResponse.Message = "Se modifico satisfactoriamente";

              }
              catch (Exception ex)
              {
                  jsonResponse.Success = false;
                  jsonResponse.Message = "No se pudo modificar el registro." + ex.Message;
              }
              return Json(jsonResponse, JsonRequestBehavior.AllowGet);
          }

          [HttpPost]
          public JsonResult DeleteJqGrid(int id)
          {
              var jsonResponse = new JsonResponse();
              try
              {
                  LocalBL.Instancia.Eliminar(id);
                  jsonResponse.Success = true;
                  jsonResponse.Message = "Se eliminó satisfactoriamente";

              }
              catch (Exception ex)
              {
                  jsonResponse.Success = false;
                  jsonResponse.Message = "No se pudo eliminar el registro." + ex.Message;
              }
              return Json(jsonResponse, JsonRequestBehavior.AllowGet);
          }

    }
}

SistemaRestaurante/Source/Presentation Layer/SistemaRestaurante.WebSite/Views/Local/Create.cshtml
@model SistemaRestaurante.BusinessEntity.Local

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>

<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

@using (Html.BeginForm("Create","Local",FormMethod.Post, new {id= "frmRegistroLocal" })) {
    @Html.ValidationSummary(true)
    <fieldset>
        <legend>Local</legend>

        

        <div class="editor-label">
            @Html.LabelFor(model => model.Nombre)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Nombre)
            @Html.ValidationMessageFor(model => model.Nombre)
        </div>
        
          <div class="editor-label">
            @Html.LabelFor(model => model.Provincia)
        </div>
        <div class="editor-field">
            @Html.DropDownListFor(model => model.Provincia, ViewBag.Provincias as SelectList, "- Seleccionar -" )
            @Html.ValidationMessageFor(model => model.Distrito)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Distrito)
        </div>
        <div class="editor-field">
            @Html.DropDownListFor(model => model.Distrito, new List<SelectListItem>())
            @Html.ValidationMessageFor(model => model.Distrito)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Direccion)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Direccion)
            @Html.ValidationMessageFor(model => model.Direccion)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Telefono)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Telefono)
            @Html.ValidationMessageFor(model => model.Telefono)
        </div>

        <p>
            <input type="submit" value="Create" id="btnRegistrar" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>


<script type="text/javascript">

    $(document).ready(function () {

        $('#Provincia').change(function () {

            $.getJSON('/Local/Distritos/' + $('#Provincia').val(), function (data) {
               
                var items = '<option> Seleccionar un distrito</option>';
                $.each(data, function (i, distrito) {
                    items += "<option value='" + distrito.Value + "'>" + distrito.Text + "</option>";
                });
                $('#Distrito').html(items);
            });

        });


        $('#btnRegistrar').click(function (e) {

            if ($('#frmRegistroLocal').validate().form()) {
                alert('Correcto');
            } else {
                e.preventDefault();
            }
        });
    });
</script>

SistemaRestaurante/Source/Presentation Layer/SistemaRestaurante.WebSite/Views/Local/Delete.cshtml
@model SistemaRestaurante.BusinessEntity.Local

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>Local</legend>

    @Html.HiddenFor(model=>model.IdLocal)

    <div class="display-label">Nombre</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Nombre)
    </div>

    <div class="display-label">Distrito</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Distrito)
    </div>

    <div class="display-label">Direccion</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Direccion)
    </div>

    <div class="display-label">Telefono</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Telefono)
    </div>
</fieldset>
@using (Html.BeginForm()) {
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

SistemaRestaurante/Source/Presentation Layer/SistemaRestaurante.WebSite/Views/Local/Details.cshtml
@model SistemaRestaurante.BusinessEntity.Local

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<fieldset>
    <legend>Local</legend>

   @Html.HiddenFor(model=>model.IdLocal)

    <div class="display-label">Nombre</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Nombre)
    </div>

    <div class="display-label">Distrito</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Distrito)
    </div>

    <div class="display-label">Direccion</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Direccion)
    </div>

    <div class="display-label">Telefono</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Telefono)
    </div>
</fieldset>
<p>
    @Html.ActionLink("Edit", "Edit", new { idLocal=Model.IdLocal }) |
    @Html.ActionLink("Back to List", "Index")
</p>

SistemaRestaurante/Source/Presentation Layer/SistemaRestaurante.WebSite/Views/Local/Edit.cshtml
@model SistemaRestaurante.BusinessEntity.Local

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>

<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)
    <fieldset>
        <legend>Local</legend>
        @Html.HiddenFor(model => model.IdLocal)
       

        <div class="editor-label">
            @Html.LabelFor(model => model.Nombre)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Nombre)
            @Html.ValidationMessageFor(model => model.Nombre)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Distrito)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Distrito)
            @Html.ValidationMessageFor(model => model.Distrito)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Direccion)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Direccion)
            @Html.ValidationMessageFor(model => model.Direccion)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Telefono)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Telefono)
            @Html.ValidationMessageFor(model => model.Telefono)
        </div>

        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

SistemaRestaurante/Source/Presentation Layer/SistemaRestaurante.WebSite/Views/Local/Listado.cshtml
@model IEnumerable<SistemaRestaurante.BusinessEntity.Local>

@{
    ViewBag.Title = "Listado";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Listado</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table>
    <tr>
        <th>
            IdLocal
        </th>
        <th>
            Nombre
        </th>
        <th>
            Distrito
        </th>
        <th>
            Direccion
        </th>
        <th>
            Telefono
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.IdLocal)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Nombre)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Distrito)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Direccion)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Telefono)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new {  idLocal=item.IdLocal }) |
            @Html.ActionLink("Details", "Details", new {  idLocal=item.IdLocal }) |
            @Html.ActionLink("Delete", "Delete", new {  idLocal=item.IdLocal })
        </td>
    </tr>
}

</table>


<script>


</script>

SistemaRestaurante/Source/Presentation Layer/SistemaRestaurante.WebSite/Views/Local/ListadoJqgrid.cshtml
@{
    ViewBag.Title = "Listado con jQGrid";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<script src="@Url.Content("~/Scripts/jquery.jqGrid.src.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/grid.locale-es.js")" type="text/javascript"></script>
<link href="@Url.Content("~/Content/ui.jqgrid.css")" rel="stylesheet" type="text/css" />
<table id="tabla">
</table>
<div id="barra">
</div>
<script type="text/javascript">
    jQuery("#tabla").jqGrid({
        url: '@Url.Action("Listar")',
        datatype: 'json',
        mtype: 'post',
        autowidth: true,
        colNames: ['ID', 'Nombre', 'Direccion','Distrito', 'Telefono'],
        colModel: [
            { name: 'IdLocal', index: 'IdLocal', width: 60, hidden: true, editable: true, align: 'center', searchoptions: { sopt: ['eq']} }
            , { name: 'Nombre', index: 'Nombre', width: 150, editable: true,  editoptions: { size: 30, maxlength: 200 }, editrules: { required: true }, formoptions: { elmprefix: '(*)' }, searchoptions: { sopt: ['bw', 'bn']} }
            , { name: 'Direccion', index: 'Direccion', width: 100, editable: true, editoptions: { size: 30, maxlength: 200 }, editrules: { required: true }, formoptions: { elmprefix: '(*)' }, searchoptions: { sopt: ['bw', 'bn']} }
            , { name: 'Distrito', index: 'Distrito', width: 100, editable: true, editoptions: { size: 30, maxlength: 200 }, editrules: { required: true }, formoptions: { elmprefix: '(*)' }, searchoptions: { sopt: ['bw', 'bn']} }
          
            , { name: 'Telefono', index: 'Telefono', width: 70, editable: true, editoptions: { size: 20, maxlength: 11 }, searchoptions: { sopt: ['bw', 'bn']} }
              ],
        rowNum: 20,
        rowList: [20, 50, 100, 150, 200],
        pager: '#barra',
        sortname: 'IdLocal',
        viewrecords: true,
        sortorder: 'desc',
        width: '100%',
        height: '300',
        caption: 'Listado de Locales'
    });
    jQuery("#tabla").jqGrid(
        'navGrid',
        '#barra',
        { edit: true, add: true, del: true, search: true, refresh: true },
        { url: '@Url.Action("EditJqGrid")', afterSubmit: function (response, postdata) { return getResponseData(response); } },
        { url: '@Url.Action("CreateJqGrid")', afterSubmit: function (response, postdata) { return getResponseData(response); } },
        { url: '@Url.Action("DeleteJqGrid")', afterSubmit: function (response, postdata) { return getResponseData(response); } },
        { multipleSearch: false });

    function getResponseData(resp) {
        var json = resp.responseText;
        var result = eval('(' + json + ')');
        return [result.Success, result.Message, null];
    }
</script>