SistemaRestaurante/Source/Presentation Layer/SistemaRestaurante.WebSite/Controllers/PedidoAjaxController.cs
using System;
using System.Collections.Generic;

using System.Web.Mvc;
using SistemaRestaurante.BusinessEntity;
using SistemaRestaurante.BusinessLogic;
using SistemaRestaurante.Utils;
using SistemaRestaurante.Utils.Enums;

namespace SistemaRestaurante.WebSite.Controllers
{
    public class PedidoAjaxController : Controller
    {
        public IList<DetallePedido> DetallePedidos
        {
            get { return Session["DetallePedido"] as List<DetallePedido>; }
            set { Session["DetallePedido"] = value; }

        } 
        //
        // GET: /PedidoAjax/

        public ActionResult Index()
        {
            var listados = PedidoBL.Instancia.Listar();
            return View(listados);
        }

        public PartialViewResult Create()
        {
            DetallePedidos = new List<DetallePedido>();

            var entidad = new Pedido
            {
                Clientes = ClienteBL.Instancia.Listar(),
                Locales = LocalBL.Instancia.Listar(),
                DetallePedido = DetallePedidos,
                FechaString = DateTime.Now.ToShortDateString(),
                Fecha = DateTime.Now
            };
            PrepararDatos(ref entidad);
            return PartialView(entidad);
        }
        
        [HttpPost]
        public JsonResult Create(Pedido pedido)
        {
            var jsonResponse = new JsonResponse();

            if(ModelState.IsValid)
            {
                try
                {
                    pedido.DetallePedido = DetallePedidos;
                    pedido.Fecha = Convert.ToDateTime(pedido.FechaString);

                    PedidoBL.Instancia.Agregar(pedido);
                    //TODO: insertar en la BD

                    jsonResponse.Success = true;
                    jsonResponse.Message = "Se agregó con Exito";
                }
                catch(Exception ex )
                {
                    jsonResponse.Message = ex.Message;
                }
            }
            return Json(jsonResponse, JsonRequestBehavior.AllowGet);
        }

        public ActionResult CreateDetalle()
        {
            var detalle = new DetallePedido
            {
                Productos = ProductoBL.Instancia.Listar(),
                NombreProducto = string.Empty,
            };
            return PartialView(detalle);
        }

        [HttpPost]
        public PartialViewResult CreateDetalle(DetallePedido detalle)
        {
            var item = DetallePedidos.Count + 1;
            var nombreProducto = ProductoBL.Instancia.Obtener(detalle.IdProducto).Nombre;
            detalle.NombreProducto = nombreProducto;
            detalle.IdItem = item;
            DetallePedidos.Add(detalle);
            return PartialView("ListadoDetalle", DetallePedidos);
        }

        public void PrepararDatos(ref Pedido pedido)
        {
            pedido.TiposPedidos = Utils.Utils.EnumToList<TipoPedido>();

        }
    }
}

SistemaRestaurante/Source/Presentation Layer/SistemaRestaurante.WebSite/Controllers/PedidoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SistemaRestaurante.BusinessEntity;
using SistemaRestaurante.BusinessLogic;
using SistemaRestaurante.Utils.Enums;

namespace SistemaRestaurante.WebSite.Controllers
{
    public class PedidoController : Controller
    {
        public IList<DetallePedido> DetallePedidos
        {
            get { return Session["DetallePedido"] as List<DetallePedido>; }
            set { Session["DetallePedido"] = value; }

        } 
       public ActionResult Index()
       {
           var listados = PedidoBL.Instancia.Listar();
           return View(listados);
       }

        public ActionResult Create()
        {
            DetallePedidos = new List<DetallePedido>();

            var entidad = new Pedido
                              {
                                  Clientes = ClienteBL.Instancia.Listar(),
                                  Locales = LocalBL.Instancia.Listar(),
                                  DetallePedido = DetallePedidos,
                                  Fecha = DateTime.Now,
                              };
            PrepararDatos(ref entidad);
            return View(entidad);
        }

        public ActionResult CreateDetalle()
        {
            var detalle = new DetallePedido
                              {
                                  Productos = ProductoBL.Instancia.Listar(),
                                  NombreProducto = string.Empty,
                              };
            return PartialView(detalle);
        }

        [HttpPost]
        public PartialViewResult CreateDetalle(DetallePedido detalle)
        {
            var item = DetallePedidos.Count+1;
            var nombreProducto = ProductoBL.Instancia.Obtener(detalle.IdProducto).Nombre;
            detalle.NombreProducto = nombreProducto;
            detalle.IdItem = item;
            DetallePedidos.Add(detalle);
            return PartialView("ListadoDetalle", DetallePedidos);
        }

        public void PrepararDatos(ref Pedido pedido)
        {
            pedido.TiposPedidos = Utils.Utils.EnumToList<TipoPedido>();
            
        }
    }
}

SistemaRestaurante/Source/Presentation Layer/SistemaRestaurante.WebSite/Views/PedidoAjax/Create.cshtml
@model SistemaRestaurante.BusinessEntity.Pedido

<script type="text/javascript" src="@Url.Content("~/Scripts/jquery.unobtrusive-ajax.js")"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>
<h2>
    Create</h2>

<fieldset>
    <legend>Pedido</legend>
    @using (Html.BeginForm("Create","PedidoAjax", FormMethod.Post, new { id = "frmRegistrar"}))
    {
        @Html.ValidationSummary(true)
  
        <div class="editor-label">
            @Html.LabelFor(model => model.IdCliente)
        </div>
        <div class="editor-field">
            @Html.DropDownListFor(model => model.IdCliente, new SelectList(Model.Clientes, "IdCliente", "Nombre", Model.IdCliente))
            @Html.ValidationMessageFor(model => model.IdCliente)
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.IdLocal)
        </div>
        <div class="editor-field">
            @Html.DropDownListFor(model => model.IdLocal, new SelectList(Model.Locales, "IdLocal", "Nombre", Model.IdLocal))
            @Html.ValidationMessageFor(model => model.IdLocal)
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.FechaString)
        </div>
        <div class="editor-field">
            @Html.TextBoxFor(model => model.FechaString, new { @class = "calendar" })
            @Html.ValidationMessageFor(model => model.FechaString)
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.TipoPedido)
        </div>
        <div class="editor-field">
            @Html.DropDownListFor(model => model.TipoPedido, new SelectList(Model.TiposPedidos, "Id","Nombre",Model.TipoPedido))
            @Html.ValidationMessageFor(model => model.TipoPedido)
        </div>
       
        
        <p>
            <input type="submit" value="Create" id = "btnRegistrar" />
        </p>
   
    }

@Ajax.ActionLink("Agregar Detalle", "CreateDetalle", "Pedido", new AjaxOptions
{
    HttpMethod = "GET",
    UpdateTargetId = "informacion",
    OnComplete = "OnCompleteCreateDetalle"
})

    <div id="listado">
        @{Html.RenderPartial("ListadoDetalle", Model.DetallePedido);}
    </div>

    <div id="informacion">
    </div>

    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</fieldset>

<script type="text/javascript">

    $(function () {

        $("input.calendar").datepicker({
            dateFormat : 'dd/mm/yy', 
            changeYear : true,
            changeMonth : true,
        });
        

        $('#btnRegistrar').click(function (e) {

            if ($('#frmRegistrar').validate().form()) {

                var url = $('#frmRegistrar').attr("action");
                var parametros = $('#frmRegistrar').serialize();

                $.post(url, parametros, function(response) {
                                debugger;
                    if(response.Success) {
                        alert(response.Message);
                        window.location = '@Url.Action("Index")';
                    } else {
                        alert(response.Message);
                    }

                });
            }
            
            e.preventDefault();
            
        });
    });

    function OnCompleteCreateDetalle() {
        $('#informacion').show();
    }

</script>

SistemaRestaurante/Source/Presentation Layer/SistemaRestaurante.WebSite/Views/PedidoAjax/CreateDetalle.cshtml
@model SistemaRestaurante.BusinessEntity.DetallePedido

<div id="loadingPost" style="display: none;"> Procesando Solicitud! ...</div>

@using (Ajax.BeginForm("CreateDetalle", "Pedido", new AjaxOptions
                                                 {
                                                     HttpMethod = "POST",
                                                     InsertionMode = InsertionMode.Replace,
                                                     UpdateTargetId = "listado",
                                                     LoadingElementId = "loadingPost",
                                                     OnComplete = "OnComplete"
                                                 }))
    {
    <fieldset>
        <legend>DetallePedido</legend>
        
        <div class="editor-label">
            @Html.LabelFor(model => model.IdProducto)
        </div>
        <div class="editor-field">
            @Html.DropDownListFor(model => model.IdProducto, new SelectList(Model.Productos, "IdProducto","Nombre", Model.IdProducto))
            @Html.ValidationMessageFor(model => model.IdProducto)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Cantidad)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Cantidad)
            @Html.ValidationMessageFor(model => model.Cantidad)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Precio)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Precio)
            @Html.ValidationMessageFor(model => model.Precio)
        </div>
       
        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

<script type="text/javascript">
    function OnComplete() {
        $("#informacion").hide();
    }
</script>

SistemaRestaurante/Source/Presentation Layer/SistemaRestaurante.WebSite/Views/PedidoAjax/Index.cshtml
@model IEnumerable<SistemaRestaurante.BusinessEntity.Pedido>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    <a href="javascript:void(0);" id="linkMostrar">Crear nuevo pedido</a>
</p>

<div id="informacionPadre" style="display: none;"></div>

<table>
    <tr>
        <th>
            IdPedido
        </th>
        <th>
            Fecha
        </th>
        <th>
            TipoPedido
        </th>
        <th>
            Cliente
        </th>
        <th>
            Local
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.IdPedido)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Fecha)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TipoPedido)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Cliente)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Local)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
            @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
            @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
        </td>
    </tr>
}

</table>

<script type="text/javascript">

    $(function () {

        $('#informacionPadre').dialog({
            width: 'auto',
            resizable: false,
            modal: true,
            autoOpen: false
        });

        $('#linkMostrar').click(function (e) {
            var url = '@Url.Action("Create","PedidoAjax")';

            $.ajax({
                type: "GET",
                url: url,
                async: false,
                dataType: "html",
                success: function (resultado) {
                    $('#informacionPadre').html(resultado);
                    $('#informacionPadre').dialog('open');
                },
                error: function (request, status, error) {
                    
                    
                    alert(request.responseText);
                }
            });
        });
    });

</script>

SistemaRestaurante/Source/Presentation Layer/SistemaRestaurante.WebSite/Views/PedidoAjax/ListadoDetalle.cshtml
@model  IList<SistemaRestaurante.BusinessEntity.DetallePedido>

<table>
    <tr>
        
        <th>
            IdItem
        </th>
       
        <th>
            Cantidad
        </th>
        <th>
            Precio
        </th>
        <th>
            NombreProducto
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        
        <td>
            @Html.DisplayFor(modelItem => item.IdItem)
        </td>
        
        <td>
            @Html.DisplayFor(modelItem => item.Cantidad)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Precio)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.NombreProducto)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
            @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
            @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
        </td>
    </tr>
}

</table>