SistemaRestaurante/Source/Presentation Layer/SistemaRestaurante.WebSite/Controllers/ReporteController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using SistemaRestaurante.WebSite.Core;
using SistemaRestaurante.BusinessLogic;

namespace SistemaRestaurante.WebSite.Controllers
{
    public class ReporteController : BaseController
    {
        //
        // GET: /Reporte/
        public ActionResult ReporteLocales()
        {
            return View("ReporteLocales");
        }


        public ActionResult ExportarLocales(string formato)
        {
            var datos = LocalBL.Instancia.Listar();
            RenderReport("rptLocales","DSLocal",datos,formato);
            return View("ReporteLocales");
        }

        public ActionResult GraficoJs()
        {
            return View();
        }

        public JsonResult ObtenerPorcentajeVentas()
        {
            var datos = PedidoBL.Instancia.PedidosDiarios();
            return Json(datos.ToArray(), JsonRequestBehavior.AllowGet);
        }
    }
}

SistemaRestaurante/Source/Presentation Layer/SistemaRestaurante.WebSite/Views/Reporte/GraficoJs.cshtml
@{
    ViewBag.Title = "GraficoJs";
}

<script src="@Url.Content("~/Scripts/highcharts.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/modules/exporting.js")" type="text/javascript"></script>


<h2>Grafico  usando Highcharts JS</h2>

<div id="container" style="width: 100%"></div>
<script type="text/javascript">
    var chart;
    $(document).ready(function () {

        var options = {
            chart: {
                renderTo: 'container',
                margin: [50, 200, 60, 170]
            },
            title: {
                text: 'Ventas diarias'
            },
            plotArea: {
                shadow: null,
                borderWidth: null,
                backgroundColor: null
            },
            tooltip: {
                formatter: function() {
                    return '<b>' + this.point.name + '</b>: ' + this.y + ' soles';
                }
            },
            plotOptions: {
                allowPointSelect: true,
                cursor: 'pointer',
                dataLabels: {
                    enabled: true,
                    formatter: function() {
                        if (this.y > 5) return this.point.name;
                    },
                    color: 'white',
                    style: {
                        font: '13px Trebuchet MS'
                    }
                }
            },
            legend: {
                layout: 'vertical',
                style: {
                    left: 'auto',
                    bottom: 'auto',
                    right: 'auto',
                    top: 'auto'
                }
            },
            series: []
        };
        
        //llamada JSON
        $.getJSON("ObtenerPorcentajeVentas", null, function(items) {
            var series = {
                type: 'pie',
                name: 'Ventas diarias',
                data: []
            };
            $.each(items, function(itemNo, item) {
                series.data.push({
                    name: item.Fecha,
                    y: parseFloat(item.Valor)
                });
            });
            options.series.push(series);
            
            //Crear el grafico
            chart = new Highcharts.Chart(options);
            chart.render();

        });
    });

</script>

SistemaRestaurante/Source/Presentation Layer/SistemaRestaurante.WebSite/Views/Reporte/ReporteLocales.cshtml
@{
    ViewBag.Title = "ReporteLocales";
}

<h2>Reporte de Locales ingresados al Sistema</h2>


<input type="button" id="btnExportar" value="Descargar Reporte EXCEL"/>

<input type="button" id="btnExportarPDF" value="Descargar Reporte PDF"/>


<script type="text/javascript">

    $(document).ready(function() {

        $('#btnExportar').bind("click", function (e) {

            var url = '@Url.Action("ExportarLocales", "Reporte")' + '?formato=EXCEL';

            window.location.href = url;
        });


        $('#btnExportarPDF').bind("click", function (e) {

            var url = '@Url.Action("ExportarLocales", "Reporte")' + '?formato=PDF';

            window.location.href = url;
        });
    });


</script>