SistemaRestaurante/Source/Presentation Layer/SistemaRestaurante.WebSite/Controllers/CategoriaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SistemaRestaurante.BusinessEntity;
using SistemaRestaurante.BusinessLogic;
using SistemaRestaurante.Utils;

namespace SistemaRestaurante.WebSite.Controllers
{
    [Authorize]
    public class CategoriaController : Controller
    {
        //
        // GET: /Categoria/

        public ActionResult Index()
        {
            var listaCategorias = CategoriaBL.Instancia.Listar();
            return View("Listado",listaCategorias);
        }

      
        public ActionResult Create()
        {
            var categoria = new Categoria();

            return View("Create", categoria);
        }

        [HttpPost]
        public ActionResult Create(Categoria categoria)
        {
            //throw new Exception("Error!!! ");
            CategoriaBL.Instancia.Agregar(categoria);

            return Content("Registro Realizado", "text/html");
            // var listaCategorias = CategoriaBL.Instancia.Listar();
            //return View("Listado", listaCategorias);
        }

        public ActionResult Edit(int idCategoria)
        {
            var categoria = CategoriaBL.Instancia.Obtener(idCategoria);

            return View("Edit", categoria);

        }

        [HttpPost]
        public ActionResult Edit (Categoria categoria)
        {
            CategoriaBL.Instancia.Modificar(categoria);

            var listaCategorias = CategoriaBL.Instancia.Listar();
            return View("Listado", listaCategorias);
        }

        public ActionResult Delete (int idCategoria)
        {
            var categoria = CategoriaBL.Instancia.Obtener(idCategoria);

            return View("Delete", categoria);
        } 

        [HttpPost]
        public ActionResult Delete (Categoria categoria)
        {
            CategoriaBL.Instancia.Eliminar(categoria.IdCategoria);

            var listaCategorias = CategoriaBL.Instancia.Listar();
            return View("Listado", listaCategorias);
        }

        public ActionResult Details (int idCategoria)
        {
            var categoria = CategoriaBL.Instancia.Obtener(idCategoria);

            return View("Details", categoria);
        }

        
    }
}

SistemaRestaurante/Source/Presentation Layer/SistemaRestaurante.WebSite/Views/Categoria/Create.cshtml
@model SistemaRestaurante.BusinessEntity.Categoria
@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2>
    Create</h2>
<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>
<script type="text/javascript" src="@Url.Content("~/Scripts/jquery.unobtrusive-ajax.js")"></script>

<div id="loadingPost" style="display: none">
    Procesando Solicitud ...</div>
<div id="target">
    

   @using(Ajax.BeginForm("Create","Categoria",new AjaxOptions
                                             {
                                                 HttpMethod = "POST",
                                                 InsertionMode = InsertionMode.InsertBefore,
                                                 UpdateTargetId = "target",
                                                 LoadingElementId = "loadingPost",
                                                 LoadingElementDuration = 3000,
                                                 OnBegin = "metodoOnBegin",
                                                 OnFailure = "metodoOnFailure",
                                                 OnSuccess = "metodoOnSuccess",
                                                 OnComplete = "metodoOnComplete"
                                             }) )
    {
    <fieldset>
        <legend>Categoria</legend>
        <div class="editor-label">
            @Html.LabelFor(model => model.Nombre)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Nombre)
            @Html.ValidationMessageFor(model => model.Nombre)
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.Imagen)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Imagen)
            @Html.ValidationMessageFor(model => model.Imagen)
        </div>
        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
    }
    
</div>
<div>
    @Html.ActionLink("Back to List", "Index")
</div>

<script type="text/javascript">

    function metodoOnBegin() {
        alert('metodoOnBegin');
        
        if($('#Nombre').val()=="Ajax") {
            return false;
        } else {
            return true;
        }
    }

    function metodoOnFailure() {
        alert('metodoOnFailure');
    }

    function metodoOnSuccess() {
        alert('metodoOnSuccess');
    }

    function metodoOnComplete() {
        alert('metodoOnComplete');
        window.location = '@Url.Action("Index","Categoria")';
    }
</script>

SistemaRestaurante/Source/Presentation Layer/SistemaRestaurante.WebSite/Views/Categoria/Delete.cshtml
@model SistemaRestaurante.BusinessEntity.Categoria

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>Categoria</legend>

        @Html.HiddenFor(model => model.IdCategoria)

    <div class="display-label">Nombre</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Nombre)
    </div>

    <div class="display-label">Imagen</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Imagen)
    </div>
</fieldset>
@using (Html.BeginForm()) {
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

SistemaRestaurante/Source/Presentation Layer/SistemaRestaurante.WebSite/Views/Categoria/Details.cshtml
@model SistemaRestaurante.BusinessEntity.Categoria

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<fieldset>
    <legend>Categoria</legend>
    
    @Html.HiddenFor(model=>model.IdCategoria)

    <div class="display-label">Nombre</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Nombre)
    </div>

    <div class="display-label">Imagen</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Imagen)
    </div>
</fieldset>
<p>
    @Html.ActionLink("Edit", "Edit", new { idCategoria = Model.IdCategoria }) |
    @Html.ActionLink("Back to List", "Index")
</p>

SistemaRestaurante/Source/Presentation Layer/SistemaRestaurante.WebSite/Views/Categoria/Edit.cshtml
@model SistemaRestaurante.BusinessEntity.Categoria

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>

<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)
    <fieldset>
        <legend>Categoria</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.Nombre)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Nombre)
            @Html.ValidationMessageFor(model => model.Nombre)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Imagen)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Imagen)
            @Html.ValidationMessageFor(model => model.Imagen)
        </div>
        
            @Html.HiddenFor(model => model.IdCategoria)
        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

SistemaRestaurante/Source/Presentation Layer/SistemaRestaurante.WebSite/Views/Categoria/Listado.cshtml
@model IEnumerable<SistemaRestaurante.BusinessEntity.Categoria>

@{
    ViewBag.Title = "Listado";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Listado</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table>
    <thead>
        <tr>
            <th>
                IdCategoria
            </th>
            <th>
                Nombre
            </th>
            <th>
                Imagen
            </th>
            <th></th>
        </tr>
    </thead>

    <tbody>
        @foreach (var item in Model) {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.IdCategoria)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Nombre)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Imagen)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { idCategoria = item.IdCategoria }) |
                    @Html.ActionLink("Details", "Details", new { idCategoria = item.IdCategoria }) |
                    @Html.ActionLink("Delete", "Delete", new { idCategoria = item.IdCategoria })
                </td>
            </tr>
        }
    </tbody>
    <tfoot>
        <tr>
            <th>
                IdCategoria
            </th>
            <th>
                Nombre
            </th>
            <th>
                Imagen
            </th>
            <th></th>
        </tr>
    </tfoot>
</table>

<script type="text/javascript">

    $(document).ready(function () {

        $("table").dataTable();

    });

</script>